In [1]:
import numpy as np

In [2]:
numbers=np.array([2,3,5,7,1])

In [3]:
numbers

array([2, 3, 5, 7, 1])

In [4]:
type(numbers)

numpy.ndarray

In [6]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.array([x for x in range(2,21,2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])