In [2]:
import numpy as np

In [8]:
grades=np.array([[97,87,78],[67,77,87],[88,98,78],[100,81,82]])

In [9]:
grades

array([[ 97,  87,  78],
       [ 67,  77,  87],
       [ 88,  98,  78],
       [100,  81,  82]])

In [10]:
grades.sum()

1020

In [11]:
grades.min()

67

In [12]:
grades.max()

100

In [13]:
grades.mean()

85.0

In [14]:
grades

array([[ 97,  87,  78],
       [ 67,  77,  87],
       [ 88,  98,  78],
       [100,  81,  82]])

In [15]:
grades.std() #standard Deviation

9.425143677065794

In [16]:
grades.var() #variance

88.83333333333333

In [17]:
grades.mean(axis=0)

array([88.  , 85.75, 81.25])

In [18]:
grades.mean(axis=1)

array([87.33333333, 77.        , 88.        , 87.66666667])

In [19]:
grades.mean?

Docstring:
a.mean(axis=None, dtype=None, out=None, keepdims=False)

Returns the average of the array elements along given axis.

Refer to `numpy.mean` for full documentation.

See Also
--------
numpy.mean : equivalent function
Type:      builtin_function_or_method


In [20]:
#Exercise


In [21]:
grades=np.random.randint(60,101,12).reshape(3,4)

In [22]:
grades

array([[ 73, 100,  96,  69],
       [ 72,  71,  69,  61],
       [ 67,  74,  75,  80]])

In [23]:
grades.mean()

75.58333333333333

In [24]:
grades.mean(axis=0)

array([70.66666667, 81.66666667, 80.        , 70.        ])

In [25]:
grades.mean(axis=1)

array([84.5 , 68.25, 74.  ])