In [1]:
import numpy as np

In [2]:
grades =np.array([[98,67,56],[56,77,88]])

In [3]:
grades.T


array([[98, 56],
       [67, 77],
       [56, 88]])

In [4]:
#Horizontal and Vertical Stacking

In [5]:
grades

array([[98, 67, 56],
       [56, 77, 88]])

In [6]:
grades2=grades

In [7]:
grades2

array([[98, 67, 56],
       [56, 77, 88]])

In [8]:
np.hstack((grades,grades2))

array([[98, 67, 56, 98, 67, 56],
       [56, 77, 88, 56, 77, 88]])

In [9]:
np.vstack((grades,grades2))

array([[98, 67, 56],
       [56, 77, 88],
       [98, 67, 56],
       [56, 77, 88]])

In [10]:
#Exercise

In [11]:
a=np.arange(1,7).reshape(2,3)

In [12]:
a=np.hstack((a,a))

In [13]:
a=np.vstack((a,a))

In [14]:
a

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])